name: Alexis's Blog
author: Alexis de Talhouët
baseurl: 
description: Technology's thoughts
github: http://www.github.com/adetalhouet
twitter: http://www.twitter.com/adetalhouet
facebook: http://www.facebook.com/alexisdet
linkedin: http://www.linkedin.com/in/adetalhouet
email: adetalhouet89@gmail.com
location: 45°30'31"N   73°35'16"W
disqus: adetalhouet

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
